from tkinter import *

def man():
    win=Toplevel(root)
    button=Button(win, text="none")
    button.pack()

root=Tk()
menubar=Menu(root,bg="black",fg="white")
# menubar.config(background="black")

# File menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="File", menu=m1,background="black",foreground="white")
m1.add_command(label="New Project",command=man)
m1.add_command(label="New",command=man, accelerator="Alt+insert")
m1.add_command(label="New Scratch File",command=man, accelerator="Ctrl+Alt+Shift+insert")
m1.add_command(label="Open",command=man)
m1.add_command(label="Save as",command=man)
m1.add_command(label="Open Recent",command=man)
m1.add_command(label="Close Project",command=man)
m1.add_command(label="Rename Project",command=man)
m1.add_separator()
m1.add_command(label="Setting",command=man,accelerator="Ctrl+Alt+S")
# Sub menu
submenu=Menu(m1,tearoff=0)
submenu.add_command(label="File Encoding")
submenu.add_command(label="Remove BOM",foreground="Grey")
submenu.add_command(label="Add BOM")
submenu.add_command(label="Associate With File Type.... ")
submenu.add_command(label="Make File Read Only")
 # subsubmenu
subsub=Menu(submenu,tearoff=0)
subsub.add_command(label="CRLF", foreground="grey")
subsub.add_command(label="LF")
subsub.add_command(label="CR")
submenu.add_cascade(label="Line Seprator", menu=subsub)
m1.add_cascade(label="File Propertied",menu=submenu)
m1.add_separator()
# Local history sub menu
submenul=Menu(m1,tearoff=0)
submenul.add_command(label="Show History")
submenul.add_command(label="Show History For Selection")
submenul.add_command(label="Put Lable")
m1.add_cascade(label="Local History", menu=submenul)
m1.add_separator()
m1.add_command(label="Save All",command=man,accelerator="Ctrl+s")
m1.add_command(label="Reload All from Disk",command=man, accelerator="Ctrl+Alt+A")
m1.add_command(label="Repair IDE",command=man)
m1.add_command(label="Invalid Caches",command=man)
m1.add_separator()
# IDE submenu
submenui=Menu(m1,tearoff=0)
submenui.add_command(label="Import Setting")
submenui.add_command(label="Export setting")
submenui.add_separator()
submenui.add_command(label="Restore Default Setting")
submenui.add_command(label="Setting Repository")
submenui.add_command(label="Sync With Setting Repository", foreground="grey")
m1.add_cascade(label="Manage IDE setting",menu=submenui)
m1.add_command(label="New Project Setup",command=man)
m1.add_command(label="Save File as Template",command=man)
m1.add_separator()
m1.add_command(label="Export",command=man)
m1.add_command(label="Print",command=man)
m1.add_separator()
m1.add_command(label="Power save mode")
m1.add_separator()
m1.add_command(label="Exit", accelerator="Cltr+Q")

# Edit menu
m2=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Eidt", menu=m2, underline=0)
m2.add_command(label="Undo Typing",command=man, accelerator="Ctrl+Z")
m2.add_command(label="Redo",command=man,accelerator="Ctrl+Shift+Z")
m2.add_separator()
m2.add_command(label="Cut",command=man)
m2.add_command(label="Copy",command=man)
m2.add_command(label="Copy Path/Reference",command=man)
# Paste Submenu
Psubmenu=Menu(menubar,tearoff=0)
Psubmenu.add_command(label="Paste", underline=0,accelerator="Ctrl+v")
Psubmenu.add_command(label="Paste from History", underline=0,accelerator="Ctrl+Shift+v")
Psubmenu.add_command(label="Paste as test plain", underline=0,accelerator="Ctrl++Alt+Shift+v")
m2.add_cascade(label="Paste",menu=Psubmenu)
m2.add_command(label="Delete",command=man, accelerator="Delete")
m2.add_separator()
# File submenu
fsub=Menu(menubar,tearoff=0)
fsub.add_command(label="Find", accelerator="Ctrl+F")
fsub.add_command(label="Replace", accelerator="Ctrl+R")
fsub.add_command(label="Find Next Occurrence", accelerator="F3")
fsub.add_command(label="Find Previous Occurrence", accelerator="Shift+F3")
fsub.add_command(label="Select All Occurrence", accelerator="Ctrl+Alt+Shift+J")
fsub.add_command(label="Add Selection for Next Occurrence", accelerator="Alt+J")
fsub.add_command(label="Unselect Occurrence", accelerator="Alt+Shift+J")
fsub.add_command(label="Search In Selection", accelerator="Ctrl+Alt+E", foreground="grey")
fsub.add_separator()
fsub.add_command(label="Next Occurrence of the Word at Caret", accelerator="Ctrl+F3")
fsub.add_command(label="Previous Occurrence of the Word at Caret", accelerator="Ctrl+Shift+F3")
fsub.add_separator()
fsub.add_command(label="Find in Files...", accelerator="Ctrl+Shift+F")
fsub.add_command(label="Replace in Files", accelerator="Ctrl+Shift+R")
fsub.add_command(label="Evaluate JSONPath Expression")
m2.add_cascade(label="Find",menu=fsub)
# Find subusages submenu
fisub=Menu(menubar,tearoff=0)
fisub.add_command(label="Find Usages",accelerator="Alt+F7")
fisub.add_command(label="Find Usages Settings...",accelerator="Ctrl+Alt+Shift+F7")
fisub.add_command(label="Show Usages",accelerator="ctrl+Alt+F7")
fisub.add_separator()
fisub.add_command(label="Find Usages in File",accelerator="ctrl+F7")
fisub.add_command(label="Heightlight Usages in File",accelerator="Ctrl+Shift+F7")
fisub.add_command(label="Next Highlighted Usages")
fisub.add_command(label="Previous Highlightes Usages")
fisub.add_command(label="Recent Find Usages",foreground="grey")
m2.add_cascade(label="Find Usages", menu=fisub)
m2.add_separator()
m2.add_command(label="Coloumn Selection Mode",command=man,accelerator="Alt+Shift+Insert")
m2.add_command(label="Select All",command=man,accelerator="Ctrl+A")
m2.add_command(label="Add Cartes To End Selected Lines", accelerator="Alt+Shift+G",command=man)
m2.add_command(label="Extended Selection",accelerator="Ctrl+W",command=man)
m2.add_command(label="Shrink selection",accelerator="Ctrl+Shift+W",command=man)
m2.add_separator()
m2.add_command(label="Toggle Case",accelerator="Ctrl+Shift+U",command=man)
m2.add_command(label="Joint lines",accelerator="Ctrl+Shift+J",command=man)
m2.add_command(label="Duplicate Lines",accelerator="Ctrl+F",command=man)
m2.add_command(label="Fill Paragraph",command=man)
m2.add_command(label="Sort Lines",command=man)
m2.add_command(label="Reverse Lines",command=man)
m2.add_command(label="Transpose",command=man)
m2.add_separator()
m2.add_command(label="Indent Selection",accelerator="Tab",command=man,foreground="grey")
m2.add_command(label="unindent Lines or Selection",accelerator="Shift+Tab",command=man)
# Convert submenu
csub=Menu(menubar,tearoff=0)
csub.add_command(label="To Spaces")
csub.add_command(label="To Sub")
m2.add_cascade(label="Convert Indentes",menu=csub)
m2.add_separator()
# marcose submenu
msub=Menu(menubar,tearoff=0)
msub.add_command(label="Play Back Last Marco", foreground="grey")
msub.add_command(label="Start Marco Recording")
msub.add_command(label="Edit Marcos", foreground="grey")
msub.add_command(label="Play Saved Marcos...")
m2.add_cascade(label="Macros",menu=msub)
# Bookmarks Submenu
bsub=Menu(menubar,tearoff=0)
bsub.add_command(label="Toggle Bookmark",accelerator="F11")
bsub.add_command(label="Add Mnemonic Bookmark...",accelerator="Ctrl+F11")
bsub.add_separator()
bsub.add_command(label="Previous Line Bookmark",foreground="grey")
bsub.add_command(label="Next Line Bookmark",foreground="grey")
bsub.add_separator()
bsub.add_command(label="show line Bookmarks",accelerator="Shift+F11")
bsub.add_command(label="Go to Menmonic",accelerator="Ctrl+Shift+F11")
m2.add_cascade(label="Bookmarks",menu=bsub)
m2.add_separator()
m2.add_command(label="Encode XMl/HTML Special Character")

# View menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="View", menu=m1)
# tool Submenu
tsub=Menu(menubar,tearoff=0)
tsub.add_command(label="Commit",accelerator="Alt+0")
tsub.add_command(label="Project",accelerator="Alt+1")
tsub.add_command(label="Bookmarks",accelerator="Alt+2")
tsub.add_command(label="Find",accelerator="Alt+3")
tsub.add_command(label="Runt",accelerator="Alt+4")
tsub.add_command(label="Debug",accelerator="Alt+5")
tsub.add_command(label="Problems",accelerator="Alt+6")
tsub.add_command(label="Structure",accelerator="Alt+7")
tsub.add_command(label="Services",accelerator="Alt+8")
tsub.add_command(label="Version Control",accelerator="Alt+9")
tsub.add_command(label="Hierarchy")
tsub.add_command(label="Evaluate JSONPath")
tsub.add_command(label="Learn")
tsub.add_command(label="Python Console")
tsub.add_command(label="Python Packages")
tsub.add_command(label="Terminal",accelerator="Alt+F12")
tsub.add_command(label="TODO")
m1.add_cascade(label="Tool Windows",menu=tsub)
# Appearance Submenu
apsub=Menu(menubar,tearoff=0)
apsub.add_command(label="Enter Presentation Mode")
apsub.add_command(label="Enter Distraction Free Mode")
apsub.add_command(label="Enter Full Screen")
apsub.add_command(label="Enter Zen Mode")
apsub.add_separator()
apsub.add_command(label="Main Menu")
apsub.add_command(label="Toolbar")
apsub.add_command(label="Navigation Bar")
apsub.add_command(label="Tool Window Bar")
apsub.add_command(label="Status Bar")
# Status submenu
stsub=Menu(menubar,tearoff=0)
stsub.add_command(label="Code With Me Wire Stats")
stsub.add_command(label="Line:Column Number")
stsub.add_command(label="Line Separator")
stsub.add_command(label="File Encoding")
stsub.add_command(label="Power Save Mode")
stsub.add_command(label="Editor Selection Mode")
stsub.add_command(label="Indentation")
stsub.add_command(label="JSON Schema")
stsub.add_command(label="Python Interpreter")
stsub.add_command(label="Read-Only Attribute")
stsub.add_command(label="Memory Indicator")
apsub.add_cascade(label="status Bar Widgets",menu=stsub)
apsub.add_command(label="Details in Tree view")
apsub.add_command(label="Members In Navigation bar")
m1.add_cascade(label="Appearance",menu=apsub)
m1.add_command(label="Quick Definition",accelerator="ctrl+Shift+I",command=man)
m1.add_command(label="Quick Type Definition",command=man)
m1.add_command(label="Parameter Info",accelerator="Ctrl+P",command=man)
m1.add_command(label="Type Info",accelerator="Ctrl+Shift+P",command=man)
m1.add_command(label="Context Info",accelerator="Alt+Q",command=man)
m1.add_separator()
m1.add_command(label="Recent Files",accelerator="Ctrl+E",command=man)
m1.add_command(label="Recently Changed Files",command=man)
m1.add_command(label="Recent Locations",accelerator="Ctrl+Shift+E")
m1.add_command(label="Recent Changes",accelerator="Alt+Shift+C")
m1.add_separator()
m1.add_command(label="Compare With...",accelerator="Ctrl+D", command=man)
m1.add_command(label="Compare with Clipboard")
m1.add_separator()
m1.add_command(label="Quick Switch Scheme",accelerator="Ctrl+'",command=man)
# Active Submenu
acsub=Menu(menubar,tearoff=0)
acsub.add_command(label="Soft-Wrap")
acsub.add_separator()
acsub.add_command(label="show Whitespaces")
acsub.add_command(label="Show Line Numbers")
acsub.add_command(label="Show Gutter Icons")
acsub.add_command(label="Show Indent Guides")
acsub.add_command(label="Show Breadcrumbs")
acsub.add_command(label="Show Import Popups")
m1.add_cascade(label="Active Editor",command=man,menu=acsub)
m1.add_separator()
# Bidi Submenu
bisub=Menu(menubar,tearoff=0)
bisub.add_command(label="content-based")
bisub.add_command(label="Left-to-Right")
bisub.add_command(label="Right-to-left")
m1.add_cascade(label="Bidi Text Base Direction",command=man,menu=bisub)


#Navigate menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Navigate", menu=m1)
m1.add_command(label="Back",accelerator="Ctrl+Alt+Left",command=man)
m1.add_command(label="Forward",accelerator="Ctrl+Alt+Right",command=man,foreground="grey")
m1.add_separator()
m1.add_command(label="Search Everywhere",command=man)
m1.add_command(label="Class...",accelerator="Ctrl+N",command=man)
m1.add_command(label="File", accelerator="Ctrl+Shift+N")
m1.add_command(label="Symbol...",accelerator="Ctrl+Alt+Shift+N",command=man)
m1.add_command(label="Line:Column",accelerator="Ctrl+G",command=man)
m1.add_separator()
m1.add_command(label="Next Highlighted Error",accelerator="F2",command=man)
m1.add_command(label="Previous Highlighted Error",accelerator="Shift+F2",command=man)
m1.add_separator()
m1.add_command(label="Last Edit Location",accelerator="Ctrl+Shift+Backspace",command=man)
m1.add_command(label="Next Edit Location",command=man,foreground="grey")
m1.add_separator()
# Navigate Submenu
navsub=Menu(menubar,tearoff=0)
navsub.add_command(label="Night Method",accelerator="Alt+Down")
navsub.add_command(label="Previous Methof",accelerator="Alt+Up")
navsub.add_command(label="Move caret to Machine Brace",accelerator="Ctrl+Shift+M")
navsub.add_separator()
navsub.add_command(label="Next Live Template Parameter",foreground="grey")
navsub.add_command(label="Previous Live Template Parameter",foreground="grey")
navsub.add_command(label="Custom Folding",accelerator="Ctrl+Alt+.")
m1.add_cascade(label="Navigate in File", command=man,menu=navsub)
m1.add_separator()
m1.add_command(label="Select in...",accelerator="Alt+F1",command=man)
m1.add_command(label="Jump to Navigation bar",accelerator="Alt+home",command=man)
m1.add_separator()
m1.add_command(label="Declaration or usages",accelerator="Ctrl+B",command=man)
m1.add_command(label="Implementation",accelerator="Ctrl+Alt+B",command=man)
m1.add_command(label="Type of Declaration",accelerator="ctrl+Shift+B",command=man)
m1.add_command(label="super Method",accelerator="Ctrl+U",command=man)
m1.add_command(label="Related Symbol",accelerator="Ctrl+Alt+Home",command=man)
m1.add_separator()
m1.add_command(label="File Structure",accelerator="Ctrl+F12",command=man)
m1.add_command(label="File Path",accelerator="Ctrl+Alt+F12",command=man)
m1.add_command(label="Type Hierarchy",accelerator="Ctrl+H",foreground="Grey")
m1.add_command(label="Call Hierarchy",accelerator="ctrl+alt+H")
m1.add_separator()
m1.add_command(label="Up the Stack Trace",accelerator="Ctrl+Alt+Up",foreground="grey")
m1.add_command(label="Down the Stack Trace",accelerator="Ctrl+AltDown",foreground="grey")


# Code menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Code", menu=m1)
m1.add_command(label="New Project",command=man)
m1.add_command(label="New",command=man)
m1.add_command(label="New Scratch File",command=man)
m1.add_command(label="Open",command=man)
m1.add_command(label="Save as",command=man)
m1.add_command(label="Open Recent",command=man)
m1.add_command(label="Close Project",command=man)
m1.add_command(label="Rename Project",command=man)
m1.add_separator()
m1.add_command(label="Setting",command=man)
m1.add_command(label="File Propertied",command=man)
m1.add_separator()
m1.add_command(label="Local History", command=man)
m1.add_separator()
m1.add_command(label="Save All",command=man)
m1.add_command(label="Reload All from Disk",command=man)
m1.add_command(label="Repair IDE",command=man)
m1.add_command(label="Invalid Caches",command=man)
m1.add_separator()
m1.add_command(label="Manage IDE setting",command=man)
m1.add_command(label="New Project Setup",command=man)
m1.add_command(label="Save File as Template",command=man)
m1.add_separator()
m1.add_command(label="Export",command=man)
m1.add_command(label="Print",command=man)
m1.add_separator()
m1.add_command(label="Power save mode")
m1.add_separator()
m1.add_command(label="Exit")

#Refactor menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Refactor", menu=m1)
m1.add_command(label="Refactor This",accelerator="Ctrl+Alt+shift+T",command=man)
m1.add_command(label="Rename",accelerator="Shift+F6",command=man)
m1.add_command(label="Change signature",accelerator="Ctrl+F6",command=man)
# Extract submenu
exsub=Menu(menubar,tearoff=0)
exsub.add_command(label="Variable",accelerator="Ctrl+Alt+V")
exsub.add_command(label="Constant...",accelerator="Ctrl+Alt+C")
exsub.add_command(label="Field",accelerator="Ctrl+Alt+F")
exsub.add_command(label="Parameter...",accelerator="Ctrl+Alt+P")
exsub.add_separator()
exsub.add_command(label="Method...",accelerator="Ctrl+Alt+M")
exsub.add_separator()
exsub.add_command(label="Superclass...")
m1.add_cascade(label="Extract/Introduce",command=man,menu=exsub)
m1.add_command(label="Inline",accelerator="Ctrl+Alt+N",command=man,foreground="grey")
m1.add_separator()
m1.add_command(label="Move Files",accelerator="F6",command=man)
m1.add_command(label="Copy File",accelerator="F5",command=man)
m1.add_command(label="Safe Delete",accelerator="Alt+Delete",command=man)
m1.add_separator()
m1.add_command(label="Pull Members Up...",command=man)
m1.add_command(label="Push Members Down...",command=man)
m1.add_command(label="Invert Boolean...",foreground="grey" ,command=man)
m1.add_command(label="Covert to Python Packages",foreground="grey",command=man)
m1.add_command(label="Covert to Python Module",foreground="grey",command=man)



#Run menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Run", menu=m1)
m1.add_command(label="Run",accelerator="Alt+Shift+F10",command=man)
m1.add_command(label="Debug ",accelerator="Alt+Shift+F9",command=man)
m1.add_command(label="Attach to Process..",accelerator="Ctrl+Alt+F5",command=man)
m1.add_command(label="Edit Configuration")
m1.add_separator()
m1.add_command(label="Stop",accelerator="Ctrl+F2",command=man)
m1.add_command(label="Stop Background Processes...",accelerator="Ctrl+Shift+F2",command=man,foreground="grey")
m1.add_command(label="Show Running List",command=man)
m1.add_separator()
# Debug Submenu
desub=Menu(menubar,tearoff=0)
desub.add_command(label="",accelerator="")
m1.add_cascade(label="Debugging Actions",command=man,menu=desub)
# Toggle Submenu
tgsub=Menu(menubar,tearoff=0)
tgsub.add_command(label="",accelerator="")
m1.add_cascade(label="Toggle Breakpoint",command=man,menu=tgsub)
m1.add_command(label="View Breakpoints...",accelerator="Ctrl+Shift+F8",command=man)
m1.add_separator()
tesub=Menu(menubar,tearoff=0)
tesub.add_command(label="Line Breakpoint",accelerator="Ctrl+F8")
tesub.add_command(label="Temporary Line Breakpoint",accelerator="Ctrl+Alt+Shift+F8")
tesub.add_command(label="Toggle Breakpoint Enabled",foreground="grey")
m1.add_cascade(label="Test History",command=man,menu=tesub,foreground="grey")
m1.add_command(label="Import Test from Files.....", command=man)
m1.add_command(label="Show Coverage Data",accelerator="Ctrl+Alt+F6",command=man)


#Tools menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Tools", menu=m1)
m1.add_command(label="Tasks & Contexts",command=man)
m1.add_separator()
m1.add_command(label="Code with Me",accelerator="Ctrl+Shift+Y",command=man)
m1.add_command(label="IDE Scripting Console",command=man)
m1.add_command(label="XML Actions",command=man)
m1.add_command(label="Markdown Converter",command=man)
m1.add_command(label="Python or Debug Console",command=man)
m1.add_command(label="Sync Python Requirements...",command=man)
m1.add_command(label="Create setup.py",command=man)
m1.add_command(label="Run setup.py Tasks....",command=man)
m1.add_command(label="Sphinx Quickstart",command=man)
m1.add_command(label="Space", command=man)


#Vcs menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="VCS", menu=m1)
m1.add_command(label="Enable Version Control Integration...",command=man)
m1.add_command(label="VCS Operations",accelerator="Alt+,",command=man)
m1.add_command(label="Apply Patch...",command=man)
m1.add_command(label="Apply Patch from Clipboard",command=man)
m1.add_separator()
m1.add_command(label="Get from Version control...",command=man)
m1.add_command(label="Browse VCS Repository",command=man)
m1.add_separator()
m1.add_command(label="Create Mercurial Repository",command=man)
m1.add_command(label="Import into Subversion...",command=man)
m1.add_command(label="Share Project (Subversion)..",command=man)
m1.add_command(label="Create Git Repository",command=man)
m1.add_command(label="Share Project on GitHub", command=man)
m1.add_command(label="Share Project on space",command=man)


#Window menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Window", menu=m1)
m1.add_command(label="Store Current Layout as Default",command=man)
m1.add_command(label="Restore Default Layout",accelerator="Shift+F12",command=man)
m1.add_command(label="Active Tool Window",command=man)
m1.add_command(label="Editors Tabs",command=man)
m1.add_command(label="Notifications",command=man)
m1.add_command(label="Background Tasks",command=man)
m1.add_separator()
m1.add_command(label="Next Project Window",accelerator="Ctrl+Alt+]",command=man)
m1.add_command(label="Previous Project Window",accelerator="Ctrl+Alt+[",command=man)

#Help menu
m1=Menu(menubar,tearoff=0)
menubar.add_cascade(label="Help", menu=m1)
m1.add_command(label="Find Actions",accelerator="Ctrl+Shif+A",command=man)
m1.add_separator()
m1.add_command(label="Help",command=man)
m1.add_separator()
m1.add_command(label="Learn IDE Features",command=man)
m1.add_command(label="What's New in Pycharm",command=man)
m1.add_command(label="Getting Started",command=man)
m1.add_command(label="Pycharm on YouTube",command=man)
m1.add_command(label="Keyboard Shortcuts PDF",command=man)
m1.add_command(label="Tip of the Day",command=man)
m1.add_separator()
m1.add_command(label="My Productivity",command=man)
m1.add_separator()
m1.add_command(label="Contact Support...",command=man)
m1.add_command(label="Submit a Bug Report...", command=man)
m1.add_command(label="Submit feedback...",command=man)
m1.add_separator()
m1.add_command(label="Show Log in Explore",command=man)
m1.add_command(label="Collect Logs and Diagnostic Data",command=man)
m1.add_command(label="Delete Leftover IDE Directories...",command=man)
m1.add_separator()
m1.add_command(label="Diagnostic Tools",command=man)
m1.add_command(label="Change Memory Setting",command=man)
m1.add_command(label="Edit Custom Properties",command=man)
m1.add_command(label="Edit Custom VM Options... ")
m1.add_separator()
m1.add_command(label="Check for Updates...",command=man)
m1.add_command(label="Register Plugins",command=man)
m1.add_separator()
m1.add_command(label="About")




root.geometry("700x700")

frame = Frame(root, bg="black", width=500, height=500)
frame.pack(pady=50)
frame.pack_propagate(0)
frame.place(x=100,y=150)

tittle = Label(frame, text="Employess Data Form", fg="white", bg="black", font=("serif", 18))
tittle.pack(pady=50)

# Lables
lable1 =Label(frame, text="Employee Name:-", bg="black", fg="white", font=13)
lable1.pack(side="left")
lable1.place(x="25", y="110")

lable2 = Label(frame, text="Employee Id:-", bg="black", fg="white", font=13)
lable2.pack(side="left")
lable2.place(x="25", y="150")

lable3 = Label(frame, text="Employee Contact no:-", bg="black", fg="white", font=13)
lable3.pack(side="left")
lable3.place(x="25", y="190")

lable4 =Label(frame, text="Employee Address:-", bg="black", fg="white", font=13)
lable4.pack(side="left")
lable4.place(x="25", y="230")

lable6 =Label(frame, text="Employee Gender:-", bg="black", fg="white", font=13)
lable6.pack(side="left")
lable6.place(x="25", y="270")

lable5 = Label(frame, text="Emp location choose:-", bg="black", fg="white", font=13)
lable5.pack(side="left")
lable5.place(x="25", y="310")

# lable5 = Label(frame, text="Emp Joining Month:-", bg="black", fg="white", font=13)
# lable5.pack(side="left")
# lable5.place(x="25", y="350")

# enteries
entry = Entry(frame, width=40,)
entry.pack(side="right")
entry.place(x="195", y="112")

entry1 = Entry(frame, width=40,)
entry1.pack(side="right")
entry1.place(x="195", y="152")

entry2 = Entry(frame, width=40,)
entry2.pack(side="right")
entry2.place(x="195", y="192")

entry3 = Entry(frame, width=40,)
entry3.pack(side="right")
entry3.place(x="195", y="232")

# radiobutton
radiobutton=Radiobutton(frame, text="Male", font=8)
radiobutton.pack()
radiobutton.place(x=195,y=270)
radiobutton1=Radiobutton(frame, text="Female", font=8)
radiobutton1.pack()
radiobutton1.place(x=258,y=270)
radiobutton2=Radiobutton(frame, text="Others", font=8)
radiobutton2.pack()
radiobutton2.place(x=340,y=270)

# Checkbutton
c1 = Checkbutton(frame, text="Navi-mumbai", font=8)
c1.pack(side="left")
c1.place(x=195, y=310)
c2 = Checkbutton(frame, text="Andheri", font=8)
c2.pack(side="left")
c2.place(x=250, y=310)
c3 = Checkbutton(frame, text="Airoli",  font=8)
c3.pack(side="left")
c3.place(x=330, y=310)
c4 = Checkbutton(frame, text="Thane", font=8)
c4.pack(side="left")
c4.place(x=395, y=310)

# Combobox
# n = StringVar()
# monthchoose = tk.Combobox(root, width=43, textvariable=n, background="cyan")
# # dropdown list
#
# monthchoose['values'] = (' January',
#                          ' February',
#                          ' March',
#                          ' April',
#                          ' May',
#                          ' June',
#                          ' July',
#                          ' August',
#                          ' September',
#                          ' October',
#                          ' November',
#                          ' December',)
# # monthchoose.grid(column=9,row=5)
# # monthchoose.current()
# monthchoose.pack(side="right")
# monthchoose.place(x=240,y=400)
#

# Buttons
reset=Button(frame, text="Reset", bd=5 , width=10, font=12)
reset.pack()
reset.place(x=110, y=420)

submit=Button(frame, text="submit", bd=5, width=10, font=12)
submit.pack()
submit.place(x=250, y=420)






root.config(menu=menubar,background="black")
root.mainloop()
